// Login
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const STARTING_LOGIN_CALL = 'STARTING_LOGIN_CALL';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
// Auth
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
// New Order
export const SET_NEW_ORDER_STEP = 'SET_NEW_ORDER_STEP';
export const SET_TYPEAHEAD_CUSTOMERS = 'SET_TYPEAHEAD_CUSTOMERS';
export const SET_TYPEAHEAD_CUSTOMERS_INPUT_VALUE = 'SET_TYPEAHEAD_CUSTOMERS_INPUT_VALUE';
export const TYPEAHEAD_CUSTOMERS_INPUT_ISLOADING = 'TYPEAHEAD_CUSTOMERS_INPUT_ISLOADING';
export const SET_BILLING_ADDRESS_INPUTS_VISIBILITY = 'SET_BILLING_ADDRESS_INPUTS_VISIBILITY';
export const SET_PRODUCTS_LIST = 'SET_PRODUCTS_LIST';
export const IS_PRODUCT_LIST_LOADING = 'IS_PRODUCT_LIST_LOADING';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';
export const SAVE_PRODUCT_TABLE_FILTERS = 'SAVE_PRODUCT_TABLE_FILTERS';
// Sidebar
export const SET_EXPAND_CLASS = 'SET_EXPAND_CLASS';
// Navbar
export const SET_NAVBAR_TOGGLER_DROPDOWN = 'SET_NAVBAR_TOGGLER_DROPDOWN';
